#hello_world:
#    path:     /hello-world
#    defaults: {_controller: DIPlatformBundle:Advert:index}

di_platform_home:
    path:     /{page}
    defaults: {_controller: DIPlatformBundle:Advert:index, page:    1}
    requirements:
        page: \d*

di_platform_view:
    path:     /advert/{id}
    defaults: {_controller: DIPlatformBundle:Advert:view}
    requirements:
       id: \d+

di_platform_add:
    path:     /add
    defaults: {_controller: DIPlatformBundle:Advert:add}

di_platform_edit:
    path:    /edit/{id}
    defaults: {_controller: DIPlatformBundle:Advert:edit }
    requirements:
        id: \d+


#di_platform_view_slug:
#   path:    /{year}/{slug}.{_format}
#   defaults:
#       _controller: DIPlatformBundle:Advert:viewSlug
#       _format:    html
#   requirements:
#       year:   \d{4}
#       _format: html|xml

#di_platform_detail_client:
#   path: /customer/{id_client}
#   defaults: {_controller: DIPlatformBundle:Advert:detailCustomer}
#   requirements:
#       id_client: \d+


